### ISSUE TITLE
AlwaysEmptySet returns an immutable tracker

### ISSUE THREAD

**Issue by bitbckt** [jbellis/jamm#18]
ef518288ade33d08c366c5debbbff5b756f472f6 altered AlwaysEmptySet to return an immutable Set<T>, rather than the singleton instance of AlwaysEmptySet. When used as a tracker provider, calls to add() on the Set<T> raise UnsupportedOperationException.

**Comment by mebigfatguy** [comment]
good catch, fixed in 7fd7bf9. thanks
