### ISSUE TITLE
Support limited recursion depth on the debugging tree output

### ISSUE THREAD

**Issue by Fentonator** [jbellis/jamm#20]
Would be very nice if there was a way to set the maximum recursion depth of the tree generated by enableDebug(), for cases where it is being used as a "poor man's profiler" when dealing with objects that have a lot of collections or other object containers (and thus can end up having *very* large trees otherwise).

**Comment by blerer** [comment]
You can now specify the depth of the tree to be printed using enableDebug(int depth). If the tree is not fully printed the total size of the subtree will not be printed with each node as it does not make sense.
