### ISSUE TITLE
Tests failures with 32bit machine

### ISSUE THREAD

**Issue by puntogil** [jbellis/jamm#21]
Hi
I'm getting (jamm 0.3.1):
test/org/github/jamm/MemoryMeterTest.java
Shallow size of empty String expected:<32> but was:<24>
Deep size of empty String expected:<48> but was:<40>
Shallow size of one-character String expected:<32> but was:<24>
Deep size of one-character String expected:<56> but was:<48>
Environment:
Apache Maven 3.3.3 (NON-CANONICAL_2015-07-10T12:37:52_mockbuild; 2015-07-10T14:37:52+02:00)
Maven home: /usr/share/maven
Java version: 1.8.0_65, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-13.b17.fc23.i386/jre
Default locale: it_IT, platform encoding: UTF-8
OS name: "linux", version: "4.2.7-300.fc23.i686", arch: "i386", family: "unix"

Our builder system do not have a web access
Any ideas as to why?
Thanks in advance
Regards

**Comment by AnEmortalKid** [comment]
32 or 64bit java?

**Comment by puntogil** [comment]
32bit

**Comment by AnEmortalKid** [comment]
Ah, i think it might be thinking your platform is 64bit when you're using a 32bit JDK. There's a section in the memory meter where it tries to determine if it's 32 or 64 and returns a memory specification object. If you have time to debug through that bit or just print out what it chose that would be helpful and might help us determine where it's going wrong.

**Comment by blerer** [comment]
@ekaterinadimitrova2 would it be possible to add some tests on a 32 bit machine to our CI scripts?

**Comment by ekaterinadimitrova2** [comment]
32bits JDK versions added to the test image

**Comment by blerer** [comment]
Test looks good for 32 bits JDK.
