### ISSUE TITLE
How to understand results?

### ISSUE THREAD

**Issue by hrchu** [jbellis/jamm#26]
I use jamm to measure a big hashmap size:
```
    System.out.println(meter.measure(stats));
    System.out.println(meter.measureDeep(stats));
    System.out.println(meter.countChildren(stats));
```
The result is 
```
48
24165760
780543
```
I am surprised that the second value is large than the third one. Could you give some explain or definition?

**Comment by blerer** [comment]
`countChildren`  return the number of child objects not the size that they occupy in memory. By consequence it is normal that `measureDeep` return a larger number.

**Comment by hrchu** [comment]
See. Thanks!

**Comment by bearrito** [comment]
Sorry to raise this issue from the dead, but the units are of size are bytes?
