### ISSUE TITLE
Exception on JVM version 10+46

### ISSUE THREAD

**Issue by mariswa** [jbellis/jamm#30]
Hey! Just installed JDK 10  build 10+46 and MemoryLayoutSpecification throws an exception 

_> -- StackTrace --
> java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 5
>         at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3107)
>         at java.base/java.lang.String.substring(String.java:1873)
>         at org.github.jamm.MemoryLayoutSpecification.getEffectiveMemoryLayoutSpecification(MemoryLayoutSpecification.jav
> a:190)
>         at org.github.jamm.MemoryLayoutSpecification.<clinit>(MemoryLayoutSpecification.java:31)
> ..._

I suppose most probably it caused by version parsing code:

```
final String strSpecVersion = System.getProperty("java.specification.version");
        final boolean hasDot = strSpecVersion.indexOf('.') != -1;
        if (hasDot) {
            if ("1".equals(strSpecVersion.substring(0, strSpecVersion.indexOf('.')))) {
                // Java 1.6, 1.7, 1.8
                final String strVmVersion = System.getProperty("java.vm.version");
                final int vmVersion = Integer.parseInt(strVmVersion.substring(0, strVmVersion.indexOf('.')));
                modernJvm = vmVersion >= 17;
            }
        }
```

specifically by 
`final int vmVersion = Integer.parseInt(strVmVersion.substring(0, strVmVersion.indexOf('.')));
`
when taking index of "." w\o any check

**Comment by mebigfatguy** [comment]
the version string is just "10" i take it? Do you know what it is for jdk 9?

**Comment by mebigfatguy** [comment]
What version are you running, as the line number 190 seems off from the HEAD revision

**Comment by mariswa** [comment]
Yep, have to install 9.0.4 and it works well now

Regards
Marina

**Comment by mariswa** [comment]
On latest 2 versions of community edition (3.5 and 3.6 i think) its the same. I also was wondering why line 190 seems it doesn't look exactly the line for vm version parsing but based on exception details it looks like that

Regards
Marina

**Comment by blerer** [comment]
The new code should not suffer from that problem any more.
